services:
  vehicle-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env.local
    extra_hosts:
      - "localhost:host-gateway"
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
