name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      POSTMAN_COLLECTION_API_KEY: '${{ secrets.POSTMAN_COLLECTION_API_KEY }}'
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_REGION: '${{ secrets.AWS_REGION }}'

    steps:
      - uses: actions/checkout@v3
      - name: Run newman integration tests
        run: make integration
