name: Integration Tests

on:
    push:
        branches:
        - main

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20.4']
    env:
      POSTMAN_COLLECTION_API_KEY: '${{ secrets.POSTMAN_COLLECTION_API_KEY }}'

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run newman integration tests
        run: make integration
