name: Package

on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Application
        run: make package
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "vehicles-api"
          config-file: ${{ github.workspace }}/docker/.dive.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
