name: Package

on:
    push:
        branches:
        - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Application
        run: make package
      - name: Install Dive
        run: wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb && sudo apt install ./dive_0.9.2_linux_amd64.deb
      - name: Analyze Docker Image
        run: make dive
