name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20.4']
    env:
      PORT: '${{ secrets.PORT }}'
      TABLE_NAME: '${{ secrets.TABLE_NAME }}'
      DYNAMODB_ENDPOINT: '${{ secrets.DYNAMODB_ENDPOINT }}'
      GIN_MODE: '${{ secrets.GIN_MODE }}'
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_REGION: '${{ secrets.AWS_REGION }}'

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Start Database
        run: make start_db
      - name: Test with Go
        run: go test ./... -json > TestResults-${{ matrix.go-version }}.json
      - name: Delete Database
        run: make delete_db
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
